import { groq } from 'next-sanity';

export const homePageQuery = groq`
*[_type == "homePage"][0]{  
  heroCarousel[],  
  exploreTitle,  
  exploreTabTitle[],   
  exploreModel[]{
  tabTitle,
  models[]{
    exploreModelTitle,
    exploreModelSubtitle,
    exploreModelImg{
      ...,
      asset->{
        ...
      }
    },
    exploreModelPrice
  }
  },
  searchConcessionaireImg{
  ...,
  asset->{
    ...
  }
  },
  searchConcessionaireTitle,
  scheduleMaintenanceTitle,
  scheduleMaintenanceSubTitle,
  scheduleMaintenanceLogo,
  scheduleMaintenanceImgMobile{
    ...,
    asset->{
      ...
    }
  },
  scheduleMaintenanceImgLeft{
    ...,
    asset->{
      ...
    }
  },
  scheduleMaintenanceImgRight{
    ...,
    asset->{
      ...
    }
  },
  scheduleMaintenanceImgRightSmallDesktop{
    ...,
    asset->{
      ...
    }
  },
  subFooterImgLeft,
  subFooterTitleLeft,
  subFooterSubTitleLeft,
  subFooterLogoLeft,
  subFooterImgRight,
  subFooterTitleRight,
  subFooterSubTitleRight, 
  subFooterImgvw,
  subFooterTitlevw,
  subFooterSubTitlevw, 
  newsSectionTitle,
  news[]->{
    newsTitle,    
    subTitle,
    slug,
    headerImage{
      ...,
      asset->{
        ...
      }
    }
  }
}
`;
